/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

/**
 *
 * @author Mohamed Salem
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HOME = new javax.swing.JMenu();
        Items = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenuItem();
        ADD = new javax.swing.JMenu();
        ADD_ITEM = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        EDIT = new javax.swing.JMenu();
        EDIT_ITEM = new javax.swing.JMenuItem();
        DELETE = new javax.swing.JMenu();
        DELETE_ITEM = new javax.swing.JMenuItem();
        BUY = new javax.swing.JMenu();
        BUY_ITEM = new javax.swing.JMenuItem();
        SEARCH = new javax.swing.JMenu();
        SEARCH_ITEM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BACKGROUND.setBackground(new java.awt.Color(0, 51, 153));
        BACKGROUND.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BACKGROUND.setForeground(new java.awt.Color(0, 0, 153));
        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/Inventory-PNG-Transparent-Image.png"))); // NOI18N

        jMenuBar1.setForeground(new java.awt.Color(240, 240, 240));

        HOME.setBorder(null);
        HOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-home-64.png"))); // NOI18N
        HOME.setText("Home");
        HOME.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Items.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-in-inventory-64.png"))); // NOI18N
        Items.setText("Items");
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        HOME.add(Items);

        EXIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-exit-64.png"))); // NOI18N
        EXIT.setText("Exit");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        HOME.add(EXIT);

        jMenuBar1.add(HOME);

        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-add-property-64.png"))); // NOI18N
        ADD.setText("Add");
        ADD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ADD_ITEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD_ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-add-64 (1).png"))); // NOI18N
        ADD_ITEM.setText("Add New Item");
        ADD_ITEM.setToolTipText("");
        ADD_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_ITEMActionPerformed(evt);
            }
        });
        ADD.add(ADD_ITEM);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-add-64.png"))); // NOI18N
        jMenuItem3.setText("Add to Existing Item");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        ADD.add(jMenuItem3);

        jMenuBar1.add(ADD);

        EDIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-edit-64.png"))); // NOI18N
        EDIT.setText("Edit");
        EDIT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        EDIT_ITEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EDIT_ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-edit-file-64.png"))); // NOI18N
        EDIT_ITEM.setText("Edit Item");
        EDIT_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_ITEMActionPerformed(evt);
            }
        });
        EDIT.add(EDIT_ITEM);

        jMenuBar1.add(EDIT);

        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-delete-64.png"))); // NOI18N
        DELETE.setText("Delete");
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        DELETE_ITEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DELETE_ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-delete-64 (1).png"))); // NOI18N
        DELETE_ITEM.setText("Delete Item");
        DELETE_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE_ITEMActionPerformed(evt);
            }
        });
        DELETE.add(DELETE_ITEM);

        jMenuBar1.add(DELETE);

        BUY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-buy-upgrade-64.png"))); // NOI18N
        BUY.setText("Buy");
        BUY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        BUY_ITEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BUY_ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-buy-64.png"))); // NOI18N
        BUY_ITEM.setText("Buy Item");
        BUY_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUY_ITEMActionPerformed(evt);
            }
        });
        BUY.add(BUY_ITEM);

        jMenuBar1.add(BUY);

        SEARCH.setBackground(new java.awt.Color(0, 0, 0));
        SEARCH.setBorder(null);
        SEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-search-64.png"))); // NOI18N
        SEARCH.setText("Search");
        SEARCH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SEARCH_ITEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SEARCH_ITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorysystem/Pics/icons8-search-64 (1).png"))); // NOI18N
        SEARCH_ITEM.setText("Search for Item");
        SEARCH_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_ITEMActionPerformed(evt);
            }
        });
        SEARCH.add(SEARCH_ITEM);

        jMenuBar1.add(SEARCH);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void BUY_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUY_ITEMActionPerformed
       new BuyItem().setVisible(true);
    }//GEN-LAST:event_BUY_ITEMActionPerformed

    private void ADD_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_ITEMActionPerformed
        new AddNewItem().setVisible(true);
    }//GEN-LAST:event_ADD_ITEMActionPerformed

    private void SEARCH_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_ITEMActionPerformed
       new Search().setVisible(true);
    }//GEN-LAST:event_SEARCH_ITEMActionPerformed

    private void EDIT_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_ITEMActionPerformed
       new EditItem().setVisible(true);
    }//GEN-LAST:event_EDIT_ITEMActionPerformed

    private void DELETE_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE_ITEMActionPerformed
       new DeleteItem().setVisible(true);
    }//GEN-LAST:event_DELETE_ITEMActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        new item().setVisible(true);
    }//GEN-LAST:event_ItemsActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new AddItem().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ADD;
    private javax.swing.JMenuItem ADD_ITEM;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JMenu BUY;
    private javax.swing.JMenuItem BUY_ITEM;
    private javax.swing.JMenu DELETE;
    private javax.swing.JMenuItem DELETE_ITEM;
    private javax.swing.JMenu EDIT;
    private javax.swing.JMenuItem EDIT_ITEM;
    private javax.swing.JMenuItem EXIT;
    private javax.swing.JMenu HOME;
    private javax.swing.JMenuItem Items;
    private javax.swing.JMenu SEARCH;
    private javax.swing.JMenuItem SEARCH_ITEM;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
